Update .gitlab-ci.yml file

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -61,8 +61,17 @@ deploy:
       echo "Docker login succeeded"
       EOF
     - scp docker-compose.production.yml ${SSH_USER}@${SSH_HOST}:/home/${SSH_USER}/docker-compose.yml
-    - ssh $SSH_USER@$SSH_HOST "docker compose -f /home/${SSH_USER}/docker-compose.yml pull && docker compose -f /home/${SSH_USER}/docker-compose.yml up -d --remove-orphans"
+    - scp -r .envs/.production ${SSH_USER}@${SSH_HOST}:/home/${SSH_USER}/loan_service/.envs/.production
+    - ssh $SSH_USER@$SSH_HOST "
+        if [ ! -f /home/${SSH_USER}/loan_service/.envs/.production/.postgres ]; then
+          echo 'Error: .env file not found!'
+          exit 1
+        fi
+        docker compose -f /home/${SSH_USER}/docker-compose.yml pull &&
+        docker compose -f /home/${SSH_USER}/docker-compose.yml up -d --remove-orphans
+      "
   tags:
     - docker
   only:
     - main
+
